Using string instead of static constant for SolrClient version number
public __construct ( array $clientOptions [, string $version = "3.0" ]
)

example: $client = new SolrClient($options, "4.0");
error: $client = new SolrClient($options, "FooBar");